# Generated by Django 4.0 on 2022-01-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
